apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  password: a2lzaGdpQDEyMzQ= # base64 encoded value of 'kishgi@1234'
# Note: The password is base64 encoded for security reasons.
# To decode it, you can use the command: echo 'a2lzaGdpQDEyMzQ=' | base64 --decode